import 'package:flutter/widgets.dart';

/// Endonyms for the app's supported locales — the language's own name, as shown
/// on the primary line of a language row. Names are kept plain (no country
/// suffix); the English name from `CommLocalize.getLocaleName` disambiguates
/// regional variants on the secondary line.
class LanguageNames {
  LanguageNames._();

  static const Map<String, String> _native = {
    'en_US': 'English',
    'en_AU': 'English',
    'en_CA': 'English',
    'en_GB': 'English',
    'af_ZA': 'Afrikaans',
    'am_ET': 'አማርኛ',
    'ar_SA': 'العربية',
    'az_AZ': 'Azərbaycan dili',
    'be_BY': 'Беларуская',
    'bg_BG': 'Български',
    'bn_BD': 'বাংলা',
    'ca_ES': 'Català',
    'cs_CZ': 'Čeština',
    'da_DK': 'Dansk',
    'de_DE': 'Deutsch',
    'el_GR': 'Ελληνικά',
    'es_BR': 'Español',
    'es_ES': 'Español',
    'es_US': 'Español',
    'et_EE': 'Eesti',
    'eu_ES': 'Euskara',
    'fa_IR': 'فارسی',
    'fi_FI': 'Suomi',
    'fil_PH': 'Filipino',
    'fr_FR': 'Français',
    'fr_CA': 'Français',
    'gl_ES': 'Galego',
    'gu_IN': 'ગુજરાતી',
    'hi_IN': 'हिन्दी',
    'hr_HR': 'Hrvatski',
    'hu_HU': 'Magyar',
    'hy_AM': 'Հայերեն',
    'id_ID': 'Bahasa Indonesia',
    'is_IS': 'Íslenska',
    'it_IT': 'Italiano',
    'he_IL': 'עברית',
    'ja_JP': '日本語',
    'ka_GE': 'ქართული',
    'kk_KZ': 'Қазақ тілі',
    'km_KH': 'ខ្មែរ',
    'kn_IN': 'ಕನ್ನಡ',
    'ko_KR': '한국어',
    'ky_KG': 'Кыргызча',
    'lo_LA': 'ລາວ',
    'lt_LT': 'Lietuvių',
    'lv_LV': 'Latviešu',
    'mk_MK': 'Македонски',
    'ml_IN': 'മലയാളം',
    'mn_MN': 'Монгол',
    'mr_IN': 'मराठी',
    'ms_MY': 'Bahasa Melayu',
    'my_MM': 'မြန်မာ',
    'nb_NO': 'Norsk bokmål',
    'ne_NP': 'नेपाली',
    'nl_NL': 'Nederlands',
    'no_NO': 'Norsk',
    'pa_IN': 'ਪੰਜਾਬੀ',
    'pl_PL': 'Polski',
    'pt_BR': 'Português',
    'pt_PT': 'Português',
    'ro_RO': 'Română',
    'ru_RU': 'Русский',
    'si_LK': 'සිංහල',
    'sk_SK': 'Slovenčina',
    'sl_SI': 'Slovenščina',
    'sq_AL': 'Shqip',
    'sr_RS': 'Српски',
    'sv_SE': 'Svenska',
    'sw_KE': 'Kiswahili',
    'ta_IN': 'தமிழ்',
    'ta_LK': 'தமிழ்',
    'te_IN': 'తెలుగు',
    'th_TH': 'ไทย',
    'tr_TR': 'Türkçe',
    'uk_UA': 'Українська',
    'ur_PK': 'اردو',
    'vi_VN': 'Tiếng Việt',
    'zh_CN': '简体中文',
    'zh_HK': '繁體中文',
    'zh_TW': '繁體中文',
    'zu_ZA': 'isiZulu',
  };

  /// The locale's endonym, falling back to the language code when unmapped.
  static String nativeName(Locale locale) =>
      _native[locale.toString()] ??
      _native[locale.languageCode] ??
      locale.languageCode.toUpperCase();
}
